name: uncharted
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

<<<<<<< HEAD
  device_preview: ^1.2.0
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
=======
  flutter_svg: ^2.1.0
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8
  chiclet: ^1.2.0
>>>>>>> f49ed9fe3caf0b9ddeade8de70fa6203d53f16e7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Cinzel
      fonts:
        - asset:  assets/fonts/Cinzel-Medium.ttf
  assets:
   - assets/images/
  uses-material-design: true
